/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dreamfactory_blutooth_library_JNIUtil */

#ifndef _Included_com_dreamfactory_blutooth_library_JNIUtil
#define _Included_com_dreamfactory_blutooth_library_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dreamfactory_blutooth_library_JNIUtil
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dreamfactory_blutooth_library_JNIUtil_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_dreamfactory_blutooth_library_JNIUtil
 * Method:    convertSettingsBeforePassedToBluetooth
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dreamfactory_blutooth_library_JNIUtil_convertSettingsBeforePassedToBluetooth
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_dreamfactory_blutooth_library_JNIUtil
 * Method:    convertOtherBeforePassedToBluetooth
 * Signature: ([I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_dreamfactory_blutooth_library_JNIUtil_convertOtherBeforePassedToBluetooth
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_dreamfactory_blutooth_library_JNIUtil
 * Method:    convertSettingsFromBluetooth
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dreamfactory_blutooth_library_JNIUtil_convertSettingsFromBluetooth
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_dreamfactory_blutooth_library_JNIUtil
 * Method:    convertOtherFromBluetooth
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_dreamfactory_blutooth_library_JNIUtil_convertOtherFromBluetooth
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
